name: RPM

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Generating RPM Package    
        run: |
          dnf install libcurl-devel gcc-c++ rpmdevtools nodejs cmake git openssl-devel -y
          
          mkdir -p ./package/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
          
          printf '
          Name:           tess
          Version:        %s
          Release:        0
          Summary:        Tess is an terminal emulator

          License:        GPL
          Source0:        tess.tar.gz

          %%description
          Tess is a hackable, simple, rapid and beautiful terminal for the new era of technology.

          %%global debug_package %%{nil}

          %%prep
          %%setup -q

          %%build

          %%install
          rm -rf $RPM_BUILD_ROOT
          mkdir -p "$RPM_BUILD_ROOT/usr/bin/"
          mkdir -p "$RPM_BUILD_ROOT/usr/lib/tess/"
          mkdir -p "$RPM_BUILD_ROOT/usr/share/applications/"
          mkdir -p "$RPM_BUILD_ROOT/usr/share/pixmaps/"
          mkdir -p "$RPM_BUILD_ROOT/usr/share/kservices5/ServiceMenus/"

          cp Tess.desktop "$RPM_BUILD_ROOT/usr/share/applications/"
          cp icon.png "$RPM_BUILD_ROOT/usr/share/pixmaps/tess.png"

          cp tesshere.desktop "$RPM_BUILD_ROOT/usr/share/kservices5/ServiceMenus/"
          cp appintess.desktop "$RPM_BUILD_ROOT/usr/share/kservices5/ServiceMenus/"

          cp -r app/* "$RPM_BUILD_ROOT/usr/lib/tess/"
          ln -s "/usr/lib/tess/tess" "$RPM_BUILD_ROOT/usr/bin/tess"
          
          cp -r cli/tess-cli "$RPM_BUILD_ROOT/usr/bin/tess-cli"

          if type "$kbuildsycoca5" > /dev/null; then
            kbuildsycoca5
          fi

          %%files
          /usr/bin/*
          /usr/lib/tess/*
          /usr/share/applications/*
          /usr/share/pixmaps/*
          /usr/share/kservices5/ServiceMenus/*
              
          ' "${VERSION}" > ./package/rpmbuild/SPECS/tess.spec
          
          mkdir -p ./package/rpmbuild/SOURCES/tess-${VERSION}/app
          mkdir -p ./package/rpmbuild/SOURCES/tess-${VERSION}/cli
          
          cp Tess.desktop ./package/rpmbuild/SOURCES/tess-${VERSION}/
          cp build/icon.png ./package/rpmbuild/SOURCES/tess-${VERSION}/
          
          npm install
          npm run build
          cp -r dist/linux-unpacked/* package/rpmbuild/SOURCES/tess-${VERSION}/app/
          
          cd cli
          cmake . -B build -DBUILD_SHARED_LIBS=False
          make -C build
          cd ../
          
          cp cli/build/tess-cli package/rpmbuild/SOURCES/tess-${VERSION}/cli/tess-cli
                  
          cd package/rpmbuild/SOURCES
          tar zcvf tess.tar.gz ./*
          cd ../
          
          rpmbuild --define "_topdir `pwd`" -bb ./SPECS/tess.spec
          
        env:
          VERSION: ${{ steps.get_release.outputs.tag_name }}
        
      - name: Upload release binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./package/rpmbuild/RPMS/x86_64/tess-${{ steps.get_release.outputs.tag_name }}-0.x86_64.rpm
          asset_name: tess-${{ steps.get_release.outputs.tag_name }}-x86_64.rpm
          asset_content_type: application/octet-stream
