name: DEBIAN

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Generating DEBIAN Package    
        run: |
          sudo apt-get install libcurl4-openssl-dev cmake git

          mkdir -p package/debian/tess/usr/lib/tess/
          
          npm install
          npm run build
          cp -r dist/linux-unpacked/* package/debian/tess/usr/lib/tess/
          
          cd cli
          cmake . -B build -DBUILD_SHARED_LIBS=False
          make -C build
          cp build/tess-cli ../package/debian/tess/usr/bin/
          cd ../

          printf "Package: Tess\nVersion: ${VERSION}\nArchitecture: all\nEssential: no\nPriority: optional\nDepends: npm,nodejs\nMaintainer: Squitch\nDescription: Tess is a simple terminal for a modern age\n" > package/debian/tess/DEBIAN/control
          cd package/debian
          sudo chmod 755 tess/DEBIAN/postinst 
          dpkg-deb --build tess
        env:
          VERSION: ${{ steps.get_release.outputs.tag_name }}
        
      - name: Upload release binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./package/debian/tess.deb
          asset_name: tess-${{ steps.get_release.outputs.tag_name }}-x86_64.deb
          asset_content_type: application/octet-stream
